framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: false
    php_errors:
        log: true
    session:
        # enables the support of sessions in the app
        enabled: true

    templating: { engines: ['twig'] }