monolog:
    handlers:
        security:
            # log all messages (since debug is the lowest level)
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/security.log'
            channels: [security]

        doctrine:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/doctrine.log'
            channels: [doctrine]

        php:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/php.log'
            channels: [php]

        cache:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/cache.log'
            channels: [cache]

        main:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/%kernel.environment%.log'
            channels: ['!security', '!doctrine', '!php', '!cache']
