sonata_user:
  security_acl: true
  manager_type: orm
  #    mailer: custom.mailer.service.id
  class:
    user: App\Application\Sonata\UserBundle\Entity\User
    group: App\Application\Sonata\UserBundle\Entity\Group
#    admin:
#      user:
#        class:          App\Admin\UserAdmin
#        controller:     SonataUserBundle:UserCURD
#        translation:    SonataUserBundle