sonata_admin:
  title: 'ENSEMBLE'
  title_logo: /assets/images/Logo.png
  dashboard:
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }
  #    templates:
  #        knp_menu_template: '@SonataAdmin/Menu/sonata_menu.html.twig'
  templates:
  #        dashboard: '@SonataAdmin/Core/dashboard.html.twig'
  security:
    #handler: sonata.admin.security.handler.acl

    role_admin: ROLE_ADMIN
    role_super_admin: ROLE_SUPER_ADMIN

    # acl security information
    handler: sonata.admin.security.handler.role
    # role security information
    information:
      EDIT: EDIT
      LIST: LIST
      CREATE: CREATE
      VIEW: VIEW
      DELETE: DELETE
      EXPORT: EXPORT
      #OPERATOR: OPERATOR
      #MASTER: MASTER

    # permissions not related to an object instance and also to be available when objects do not exist
    # the DELETE admin permission means the user is allowed to batch delete objects
    #       admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
    admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT]

    # permission related to the objects
    object_permissions: [CREATE, LIST, VIEW, EDIT, DELETE, UNDELETE, MASTER]


sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]
