# Login Check
login_check:
    path: /api/v1/security/login-check

# Refresh Token
gesdinet_jwt_refresh_token:
    path: /api/v1/security/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods:    POST
sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting