App\Entity\Patient:
    properties:
        guid:
            groups: ['patient-list', 'patient']
        firstName:
            groups: ['patient-list', 'patient']
        lastName:
            groups: ['patient-list', 'patient']
        address:
            groups: [ 'patient']
        zipCode:
            groups: ['patient']
        phoneNumber:
            groups: ['patient-list', 'patient']
        status:
            groups: ['patient-list', 'patient']
        responses:
            groups: ['patient']