App\Entity\Patient:

    accessor_order: custom
    custom_accessor_order: [guid, firstName, lastName, address, zipCode, phoneNumber, status, responses, virtual_properties]

    virtual_properties:
        getGroupedResponses:
            serialized_name: responses
            type: array
            groups: ['treat']

    properties:
        guid:
            groups: ['patient-list', 'patient', 'treat']
        firstName:
            groups: ['patient-list', 'patient', 'treat']
        lastName:
            groups: ['patient-list', 'patient', 'treat']
        address:
            groups: ['patient', 'treat']
        zipCode:
            groups: ['patient', 'treat']
        phoneNumber:
            groups: ['patient-list', 'patient', 'treat']
        status:
            groups: ['patient-list', 'patient', 'treat']
        responses:
            groups: ['patient']