App\Entity\Question:
    properties:
        id:
            groups: ['question', 'patient']
        frValue:
            groups: ['question', 'patient']
        arValue:
            groups: ['question', 'patient']
        type:
            groups: ['question', 'patient']
        category:
            groups: ['question', 'patient']