App\Entity\Question:
    properties:
        id:
            groups: ['question', 'patient', 'treat']
        frValue:
            groups: ['question', 'patient', 'treat']
        arValue:
            groups: ['question', 'patient', 'treat']
        type:
            groups: ['question', 'patient', 'treat']
        category:
            groups: ['question', 'patient']